# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a95ff4809e31674eba987c70e75066a9dd2645e6731ab2bc6c33d972d06d4fdf15af05df6b6756f05657fbb474d6f5261d483dcacdaad62d92140b57c7854b9

test:
  secret_key_base: dc648d4f2e74a31d8e2286e65d79df2a986eabded2dbde0812b8be1b8fa15465975a4fe7f719fa029318908c6b25d288688810cf9d2be6de92228c173036ee23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
